Merge remote-tracking branch 'origin/dev' into V-spring-boot-app
VaolEr/GB-spring-boot-app pull request #15
Opened 2020-12-24 18:47 UTC by VaolEr

# Conflicts:
#	src/main/resources/application.properties

2020-12-24 19:30 UTC, dimio requested changes

2020-12-24 19:30 UTC, dimio commented on src/main/java/com/example/storehouse/dto/SupplierTo.java
> +@Builder
Тут можно и без билдера, в принципе. 2 поля всего. Это просто для справки.

2020-12-24 19:30 UTC, dimio commented on src/main/java/com/example/storehouse/repository/SuppliersRepository.java
> +    List<Supplier> findAll();
Если ты переопределяешь унаследованный `findAll()` - ставь `@Override`
Вообще, на мой взгляд, сейчас это не нужно, твой метод ничем не отличается от унаследованного из `JpaRepository` метода `List<T> findAll();`

2020-12-24 19:30 UTC, dimio commented on src/main/java/com/example/storehouse/repository/SuppliersRepository.java
> +    Optional<Supplier> findById(Integer id);
То же самое.

2020-12-24 19:30 UTC, dimio commented on src/main/java/com/example/storehouse/repository/SuppliersRepository.java
> +    Optional<Supplier> getSupplierById(Integer id);
Этот просто дублирует `findById(Integer id)`

2020-12-24 19:30 UTC, dimio commented on src/main/java/com/example/storehouse/service/SuppliersService.java
> +    private Supplier prepareToSave(SupplierTo supplierTo) {
Нет смысла в лишнем вызове (это тоже расходы), здесь просто возвращается TO и больше ничего не происходит. 
Лучше сразу `Supplier newSupplier = fromSupplierTo(supplierTo);`, и в `update` тоже.

2020-12-24 19:30 UTC, dimio commented on src/main/java/com/example/storehouse/util/SuppliersUtil.java
> +        return SupplierTo
Можно убрать билдер и сделать просто конструктор с 2 аргументами.

2020-12-24 19:30 UTC, dimio commented on src/main/java/com/example/storehouse/util/SuppliersUtil.java
> +    public static List<SupplierTo> toSupplierTos(List<Supplier> items) {
`items` тут явно по смыслу не подходит в качестве имени аргумента.

2020-12-24 19:30 UTC, dimio commented on src/main/java/com/example/storehouse/web/SuppliersController.java
> +@RequestMapping("${app.endpoints.suppliers.base_url}")
Посмотри в `ItemsController`, я поменял конфигурацию пути маппинга. Слей себе последнюю версию из `dev`.

2020-12-24 19:30 UTC, dimio commented on src/main/resources/application.properties
> +server.servlet.context-path=/api/v1
Перед обновлением PR - слей обновления из `dev` последние.

2020-12-24 19:30 UTC, dimio commented on src/test/idea-http-client/suppliers.http
> +### CREATE supplier with id 1011
Не уверен, что при создании будет именно этот `id` присвоен в БД.

2020-12-25 16:50 UTC, VaolEr commented on src/main/java/com/example/storehouse/web/SuppliersController.java
> +@RequestMapping("${app.endpoints.suppliers.base_url}")
А где ты их поменял? В той версии что ещё не замёрджена?

2020-12-25 16:51 UTC, VaolEr commented on src/main/resources/application.properties
> +server.servlet.context-path=/api/v1
Да вроде все слил

2020-12-25 19:53 UTC, VaolEr commented
Единственное что, там надо будет доделать - проверку на отсутствие supplier'a с запрашиваемым id для GET запроса /suppliers/{id}/items

2020-12-25 20:13 UTC, dimio requested changes

2020-12-25 20:13 UTC, dimio commented on src/main/java/com/example/storehouse/service/SuppliersService.java
> +        return new ArrayList<>(suppliersRepository.getOneById(id).getItems());
Вот это я бы заменил на вызов к ItemsRepository.  Если только список предметов отдельно нужен. Я так понял, что здесь мы хотели возвращать Supplier + его вложенные Item. По крайней мере - надо сравнить запросы, мне кажется, тут будет join ненужный или типа того. Это для памяти.

А Set почему не стал возвращать?

2020-12-25 20:13 UTC, dimio commented on src/main/java/com/example/storehouse/util/ValidationUtil.java
> +import java.util.Set;
Не вижу, где он тут применяется?

2020-12-25 20:13 UTC, dimio commented on src/main/java/com/example/storehouse/util/ValidationUtil.java
> +        }
Пусть остается, как было.

2020-12-25 20:13 UTC, dimio commented on src/main/resources/application.properties
> -app.endpoints.base_path=${app.endpoints.api.v1.path:/api/}${app.endpoints.api.v1.version}
Это надо сохранить.

2020-12-25 20:13 UTC, dimio commented on src/main/resources/application.properties
> +app.endpoints.suppliers.base_url=/suppliers
Это надо сохранить.

2020-12-25 20:13 UTC, dimio commented on src/main/resources/application.properties
> -## API settings
Это надо сохранить.

2020-12-25 20:13 UTC, dimio commented on src/main/resources/application.properties
> -# Надо будет попробовать в отдельный конфиг вынести, чтобы основной не засорять. Эта информация редко меняется.
Это надо сохранить.

2020-12-25 20:15 UTC, dimio commented on src/main/resources/application.properties
> -# Надо будет попробовать в отдельный конфиг вынести, чтобы основной не засорять. Эта информация редко меняется.
В общем - в этом файле надо оставить всё старое и добавить `app.endpoints.suppliers.base_url=/suppliers`

2020-12-25 20:18 UTC, dimio commented on src/main/java/com/example/storehouse/service/SuppliersService.java
> +        return new ArrayList<>(suppliersRepository.getOneById(id).getItems());
А, кстати - зачем там вообще Set? Мы же для `create` получаем supplier без вложенных items, и для `update` тоже.

2020-12-25 20:20 UTC, dimio commented on src/main/java/com/example/storehouse/model/Supplier.java
> +    private Set<Item> items;
Не понятно, зачем Set вместо List? Я что-то упускаю?

2020-12-26 07:51 UTC, VaolEr commented on src/main/java/com/example/storehouse/util/ValidationUtil.java
> +        }
Это CTRL+Alt+L съел

2020-12-26 07:56 UTC, VaolEr commented on src/main/resources/application.properties
> -app.endpoints.base_path=${app.endpoints.api.v1.path:/api/}${app.endpoints.api.v1.version}
По всем это надо сохранить - смерджил в свою ветку как-то криво. Я не специально это удалил.

2020-12-26 11:42 UTC, dimio approved these changes

2020-12-26 12:30 UTC, merged