Add categories controller tests
VaolEr/GB-spring-boot-app pull request #56
Opened 2021-01-11 19:07 UTC by VaolEr

2021-01-12 06:13 UTC, dimio requested changes

2021-01-12 06:13 UTC, dimio commented on src/test/java/com/example/storehouse/web/CategoriesControllerTests.java
> +        //TODO нужно корректнее проверку делать, судя по всему.
Ты же нигде `id` и `name` не проверяешь - вот и проходит.

Можно попробовать сделать так:
- В `given` уточнить условие срабатывания (для id=1000 вместо `any`) 
- `id` вынести в константу и подставлять её `TEST_CATEGORY_ID`
- `get` поддерживает переменные в пути (т.е. можно попробовать подставить путь к API категорий из настроек (заинжектив его в тест через `@Value`) + `TEST_CATEGORY_ID`
- В ответе сейчас можно проверить поля через json.path `.andExpect(jsonPath("$.data[0].id").value(equalTo(asJson( TEST_CATEGORY_ID))))` и по аналогии другие поля ответа, если надо. Прим.: путь (`$.data[0].id`) я не проверял, для примера привёл.
- Для отладки (и вообще наглядности) полезно добавлять `.andDo(print())` в запрос

Фактически, в тесте сейчас только код ответа и типа контента проверяются. Бывают варианты API, в которых на все запросы идёт ответ 200, а ошибки только в теле отдают.  Так что лучше и тело ответа проверять (на предмет того, что наш контроллер правильно формирует ответ в каждой конкретной ситуации).

2021-01-12 19:30 UTC, VaolEr commented on src/test/java/com/example/storehouse/web/CategoriesControllerTests.java
> +        //TODO нужно корректнее проверку делать, судя по всему.
Это всё сделал, заработало. Спасибо за подсказку.

2021-01-12 19:30 UTC, VaolEr commented on src/test/java/com/example/storehouse/web/CategoriesControllerTests.java
> +        //TODO нужно корректнее проверку делать, судя по всему.
Там дальше ещё вопросик возник...

2021-01-13 07:50 UTC, dimio approved these changes

2021-01-13 07:50 UTC, dimio commented on src/test/java/com/example/storehouse/web/CategoriesControllerTests.java
> +        //TODO нужно корректнее проверку делать, судя по всему.
Какой? Вроде всё ок сейчас.

2021-01-13 19:08 UTC, dimio commented on src/test/java/com/example/storehouse/web/CategoriesControllerTests.java
> +import static org.mockito.BDDMockito.given;
BDD не пользуемся, так что можно и обычные `when... thenReturn` вместо `willReturn`

2021-01-13 19:08 UTC, dimio commented on src/test/java/com/example/storehouse/web/CategoriesControllerTests.java
> +import com.sun.xml.bind.v2.TODO;
А это что и зачем?

2021-01-13 19:10 UTC, dimio commented on src/test/java/com/example/storehouse/web/CategoriesControllerTests.java
> +//               .andDo(print());
При ответе с ошибкой `data`  будет пустой

2021-01-13 19:11 UTC, VaolEr commented on src/test/java/com/example/storehouse/web/CategoriesControllerTests.java
> +//               .andDo(print());
но ответ то будет 200, а не 404

2021-01-13 19:14 UTC, VaolEr commented on src/test/java/com/example/storehouse/web/CategoriesControllerTests.java
> +import com.sun.xml.bind.v2.TODO;
А это я по-разному крутил вертел попытки, недоглядел и неиспользуемые импорты закоммитил

2021-01-13 19:22 UTC, dimio commented on src/test/java/com/example/storehouse/web/CategoriesControllerTests.java
> +//        given(categoriesService.getById(TEST_CATEGORY_ID_404)).willReturn(returnedCategory);
Ты замокал ответ сервиса и возвращаешь в нём категорию. Значит в ответе контроллера она и будет.

Чтобы получить ошибку - надо её вернуть из мока сервиса (`thenThrow()`). Ну или, если ты пользуешься BBDMockito, - как-то так: `doThrow(new Exception()).when(mockedObject).methodName()`
Сообщение для `error_message` просто в конструктор ошибки передать.

Дальше её перехватить обработчик `ControllerExceptionHandler -> handleNotFound(RuntimeException ex)` и формирует ответ с JSON внутри, который и содержит `error_message`

2021-01-13 19:23 UTC, dimio reviewed
Ответил в комментариях к файлу

2021-01-13 19:23 UTC, VaolEr commented on src/test/java/com/example/storehouse/web/CategoriesControllerTests.java
> +//        given(categoriesService.getById(TEST_CATEGORY_ID_404)).willReturn(returnedCategory);
Я понимаю что так как в отвте атегория, то я и ловлю категорию) я пробовал ошибку подставить, но моих знаний не хватило. Я чтот даже как вопрос в гугле задать не придумал.

2021-01-13 20:49 UTC, dimio commented on src/test/java/com/example/storehouse/web/CategoriesControllerTests.java
> +//        given(categoriesService.getById(TEST_CATEGORY_ID_404)).willReturn(returnedCategory);
Можем так поступить - это влить, как есть. Пока делать сервис-тесты по аналогии с `ItemsService`. Попозже добавлю тесты для `ItemsController` - на их основе сделаем тесты для остальных контроллеров.
Как вернуть ошибку (`thenThrow()`/`doThrow()` - пример кода я написал, прямо его можно и загуглить.

2021-02-12 18:58 UTC, closed without merging