Gs 55 add storehouses service tests
VaolEr/GB-spring-boot-app pull request #71
Opened 2021-01-18 17:43 UTC by VaolEr

2021-01-18 18:57 UTC, dimio requested changes

2021-01-18 18:57 UTC, dimio commented on src/test/java/com/example/storehouse/service/StorehousesServiceTests.java
> +    private ItemsRepository itemsRepository; // without this bean tests will not start
Раз в тестах не используется - здесь и не нужен. Над классом добавь аннотацию `@MockBean(ItemsRepository.class)`. И в ней бины, которые нужны для загрузки контекста Спринга, но не нужны в тестах.

2021-01-18 19:28 UTC, VaolEr commented on src/test/java/com/example/storehouse/service/StorehousesServiceTests.java
> +    private ItemsRepository itemsRepository; // without this bean tests will not start
Done

2021-01-21 17:25 UTC, dimio approved these changes

2021-01-21 18:38 UTC, merged