GS-56 add users service tests
VaolEr/GB-spring-boot-app pull request #72
Opened 2021-01-18 18:43 UTC by VaolEr

2021-01-18 20:40 UTC, dimio requested changes

2021-01-18 20:40 UTC, dimio commented on src/test/java/com/example/storehouse/service/ServiceTestData.java
> +    static final String TEST_USER_EMAIL = "testEmail.test.com";
В сервисах валидации, конечно, нет, но, если решим переиспользовать эти тестовые данные для контроллеров, - будет падать на валидации тестового адреса.

2021-01-18 20:40 UTC, dimio commented on src/test/java/com/example/storehouse/service/UsersServiceTests.java
> +        when(usersRepository.findByEmail(testUser.getEmail())).thenReturn(Optional.ofNullable(testUser));
Репозиторий возвращает `Optional`. В [документации spring data jpa также указано](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repository-query-return-types), что запрос вернёт `Optional` (со значением или пустой, если в БД ничего не найдено).
Т.е. либо `ofNullable` тут лишний, либо расскажи - зачем он? Мы не ожидаем `null` от БД.

2021-01-18 20:40 UTC, dimio commented on src/test/java/com/example/storehouse/service/UsersServiceTests.java
> +        verify(usersRepository).findById(testUser.getId());
`TEST_USER_ID`.

2021-01-18 20:40 UTC, dimio commented on src/test/java/com/example/storehouse/service/UsersServiceTests.java
> +        assertEquals(returnedUsers,testUser);
Пробел забыл перед `testUser`.

2021-01-18 20:40 UTC, dimio commented on src/test/java/com/example/storehouse/service/UsersServiceTests.java
> +        User returnedUsers = service.getById(testUser.getId());
А здесь - без `assert`...

2021-01-18 20:40 UTC, dimio commented on src/test/java/com/example/storehouse/service/UsersServiceTests.java
> +        when(usersRepository.findById(testUser.getId())).thenReturn(Optional.ofNullable(testUser));
Тот же вопрос по поводу `ofNullable`.

2021-01-18 20:40 UTC, dimio commented on src/test/java/com/example/storehouse/service/UsersServiceTests.java
> +        assert testUser.getId() != null;
Зачем? Есть же `TEST_USER_ID` - специально для тестов, и точно не `null`.

2021-01-18 20:40 UTC, dimio commented on src/test/java/com/example/storehouse/service/UsersServiceTests.java
> +        when(usersRepository.findById(testUser.getId())).thenReturn(Optional.empty());
Заглушка стоит для вызова с `testUser.getId()`, но проверяется вызов сервиса с `userId`.
Тест некорректный, а проходит он потому, что для `Optional` из мока по умолчанию возвращается `Optional.empty`.
Т.е. тест, вроде бы, и делает, что нужно, но совершенно неочевидным образом.
С тем же успехом можно заменить на `when(usersRepository.findById(anyInt()))`, но так хотя бы с первого взгляда будет понятно, что должно происходить в результате теста. Либо вовсе удалить строку `when`, но это, по-моему, наглядность и понятность теста тоже уменьшит.

2021-01-18 20:40 UTC, dimio commented on src/test/java/com/example/storehouse/service/UsersServiceTests.java
> +        User newUser = fromUserTo(newUserTo);
Надо будет добавить `prepareToSave`, мне кажется. Т.е. в сервисе происходит это преобразование при сохранении.
```
User newUser = fromUserTo(newUserTo);
User prepared = prepareToSave(newUser);
...
.thenReturn(prepared);
...
verify(usersRepository).save(prepared);
```
Можно не сейчас, надо подумать, как лучше. С `update` тоже.

2021-01-21 18:15 UTC, VaolEr commented on src/test/java/com/example/storehouse/service/UsersServiceTests.java
> +        when(usersRepository.findByEmail(testUser.getEmail())).thenReturn(Optional.ofNullable(testUser));
Я должен получить юзера. Если я пишу thenReturn(testUser) идёт ругань: Cannot resolve method 'thenReturn(com.example.storehouse.model.User)' и Idea предлагает сделать Wrap к Optional, в результате чего стоится такая конструкция.

2021-01-23 06:22 UTC, dimio commented on src/test/java/com/example/storehouse/service/UsersServiceTests.java
> +        when(usersRepository.findByEmail(testUser.getEmail())).thenReturn(Optional.ofNullable(testUser));
`Optional.of` vs `Optional.ofNullable` - вот мне непонятно, зачем тут `ofNullable`? По идее - необходимо и достаточно `of`.

2021-01-23 06:29 UTC, dimio approved these changes

2021-01-23 09:57 UTC, VaolEr commented on src/test/java/com/example/storehouse/service/UsersServiceTests.java
> +        when(usersRepository.findByEmail(testUser.getEmail())).thenReturn(Optional.ofNullable(testUser));
Да, достаточно of. Я в силу своего незнания Optional сделаk так, как подсказывает Idea.

2021-01-23 10:00 UTC, VaolEr commented on src/test/java/com/example/storehouse/service/ServiceTestData.java
> +    static final String TEST_USER_EMAIL = "testEmail.test.com";
Изменил на тестового админа.

2021-01-23 10:00 UTC, VaolEr commented on src/test/java/com/example/storehouse/service/UsersServiceTests.java
> +        verify(usersRepository).findById(testUser.getId());
+

2021-01-23 10:00 UTC, VaolEr commented on src/test/java/com/example/storehouse/service/UsersServiceTests.java
> +        verify(usersRepository).findById(testUser.getId());
Солгласен

2021-01-23 10:00 UTC, VaolEr commented on src/test/java/com/example/storehouse/service/UsersServiceTests.java
> +        assertEquals(returnedUsers,testUser);
Согласен

2021-01-23 10:00 UTC, merged