Correct update qty of items.
VaolEr/GB-spring-boot-app pull request #81
Opened 2021-01-28 19:09 UTC by VaolEr

Добавил обновление количества товаров на складе.
Возможно, сделал это не совсем логично или не в том месте, но оно работает.
Так же добавил отображение количества товаров, когда идёт запрос /storehouses/{id}/items.
И да, мой косяк, ветка называется криво....

2021-01-28 19:53 UTC, VaolEr commented
Решил проверить ещё раз и обнаружил, что если, при создании товара не был указан склад (блок storehouses_balance пустой), или товар присутствует только лишь на одном складе (storehouses_balance имеет только одну запись, а второй склад и вовсе не упоминается), то мой код ничего не обновлял. Добавил реализацию, когда нужно создать новую запись в itemsStorehouses.

2021-01-29 07:27 UTC, dimio commented
Хм, мне казалось, что ситуация "при создании товара не был указан склад" у нас не должна возникать, т.к. для нас (как системы учёта товаров) нет смысла хранить абстрактный товар без указания его наличия.

2021-01-29 08:30 UTC, dimio requested changes

2021-01-29 08:30 UTC, dimio commented on src/main/java/com/example/storehouse/service/ItemsService.java
> +                        //Можно вынести в отдельный метод
Нужно. 3 раза скопирован этот кусок - явный перебор.

2021-01-29 08:30 UTC, dimio commented on src/main/java/com/example/storehouse/repository/StorehousesRepository.java
> +    void updateItemQtyByItemStorehouseIdAndStorehouseIdAndItemId(@Param("itemId") Integer itemId,
Повторю - `@Param("itemId") Integer itemId` - это масло масляное. Имя параметра одинаковое в запросе и в вызове метода. `@Param` можно не указывать.
P.S. и `value` тоже, т.к. других свойств внутри аннотации не указано, а это - дефолтное.

2021-01-29 08:30 UTC, dimio commented on src/main/java/com/example/storehouse/repository/StorehousesRepository.java
> +    List<Integer> getCountOfStorehousesWhereItemPresent(@Param("itemId") Integer itemId);
Запрос возвращает список `id` и название `getCount` ему явно не подходит.

2021-01-29 08:30 UTC, dimio commented on src/main/java/com/example/storehouse/repository/StorehousesRepository.java
> +    Integer getStorehouseQuantityByItemAndStorehouseIds(@Param("itemId") Integer itemId, @Param("storehouseId") Integer storehouseId);
Этот запрос возвращает кол-во товара с указанным `id` на конкретном складе, а по названию так не скажешь. `getItemQuantityOnStorehouse`, например.

2021-01-29 08:30 UTC, dimio commented on src/main/java/com/example/storehouse/service/ItemsService.java
> +                        storehousesRepository.updateItemQtyByItemStorehouseIdAndStorehouseIdAndItemId(updatedItem.getId(), storehouse.getId(), itemStorehouseId, iSt.getQuantity());
Вот это место я не понял.
В моём представлении - ситуация такая:
- Таблица `items_storehouses` содержит колонки: `id`, `item_id`, `storehouse_id`
- Каждая запись в таблице характеризуется уникальным ключом, одним из двух:
  * либо это суррогатный ключ `id`
  * либо это естественный композитный ключ (`item_id` + `storehouse_id`)
- Для доступа к нужной записи достаточно использовать либо один, либо другой.
- Какой лучше - надо посмотреть лог запросов к БД. Думаю, что нужно выкинуть получение `storehousesRepository.getItemStorehousesById` и сразу обновлять количество, используя сочетание `updatedItem.getId(), storehouse.getId()`, останется один `SELECT` вместо двух.

2021-01-29 08:30 UTC, dimio commented on src/main/java/com/example/storehouse/service/ItemsService.java
> +            if (presentStorehouses.size() != 0) {
У `List` есть метод `isEmpty()`.
Но вообще это у нас где-то уровнем выше проблема. В БД не должно быть предметов, не относящихся ни к одному складу.

2021-01-29 08:30 UTC, dimio commented on src/main/java/com/example/storehouse/repository/StorehousesRepository.java
> +    Integer getItemStorehousesById(@Param("itemId") Integer itemId, @Param("storehouseId") Integer storehouseId);
В `ItemsService` написал по поводу этого метода.

2021-01-29 08:30 UTC, dimio commented on src/main/java/com/example/storehouse/service/StorehousesService.java
> +        for (ItemTo itemTo:itemTos) {
Здесь тоже пробелы вокруг `:`

2021-01-29 08:30 UTC, dimio commented on src/main/java/com/example/storehouse/dto/ItemTo.java
> +        groups = { Update.class, Delete.class, Replace.class }
В чём будет различие между `Update` и `Replace`?
Для удаления предмета (`Delete`) точно это поле нужно (`NotNull`)?

2021-01-31 10:33 UTC, dimio approved these changes

2021-01-31 10:33 UTC, dimio commented on src/main/java/com/example/storehouse/repository/StorehousesRepository.java
> +    Integer getItemQuantityOnStorehouseByItemIdAndStorehouseId(Integer itemId, @Param("storehouseId") Integer storehouseId);
Забыл один лишний `@Param` убрать.

2021-01-31 14:15 UTC, merged